config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  resources :order_statuses
  resources :order_items
  resources :orders
  resources :pixels
  resources :themes
  resources :faqs
  resources :visits
  resources :segmentations
  resources :segments
  resources :cart_items
  resources :carts
  resources :prominents
  resources :likes
  resources :uploads
  resources :specifications
  resources :profiles
  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :specs
  resources :categories
  resources :classifications
  resources :categorizations
  resources :products
  resources :businesses
  get '', to: 'home#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root 'home#index'

  match "/categories/get_children/:id" => "categories#get_children", :via => :get
  match "/categories/specs/:id" => "categories#specs", :via => :get
  match "/categories/upload/:id" => "categories#upload", :via => :get

  match "/products/upload/:id" => "products#upload", :via => :get
  match "/uploads/remoted/:id" => "uploads#remoted", :via => :get

  match "/likes/liike/:id" => "likes#liike", :via => :get
  match "/likes/disliike/:id" => "likes#disliike", :via => :get

  match "/carts/add_to_cart/:id" => "carts#add_to_cart", :via => :get
  match "/carts/remove_from_cart/:id" => "carts#remove_from_cart", :via => :get

  match "/home/settings" => "home#settings", :via => :get

  match "/segments/check/:id" => "segments#check", :via => :get
  match "/segments/change_level/:id" => "segments#change_level", :via => :get
  match "/segments/add_to_segment/:id" => "segments#add_to_segment", :via => :get
  match "/segments/remove_from_segment/:id" => "segments#remove_from_segment", :via => :get

  match "/products/search/:id" => "products#search", :via => :get

  match "/api/segments" => "api#segments", :via => :get
  match "/api/products/:id" => "api#products", :via => :get
  match "/api/business" => "api#business", :via => :get
  match "/api/new_user" => "api#new_user", :via => :post
  match "/api/my_profile" => "api#my_profile", :via => :get
  match "/api/upload_pict" => "api#upload_pict", :via => :post
  match "/api/categories" => "api#categories", :via => :get
  match "/api/paginated_products" => "api#paginated_products", :via => :get
  match "/api/slider" => "api#slider", :via => :get
  match "/api/login" => "api#login", :via => :get
  match "/api/product_picts/:id" => "api#product_picts", :via => :get
  match "/api/provinces" => "api#provinces", :via => :get
  match "/api/orders/:id" => "api#orders", :via => :get
  match "/api/my_orders" => "api#my_orders", :via => :get
  match "/api/search" => "api#search", :via => :get
  match "/api/sort" => "api#sort", :via => :get
  match "/api/order_statuses" => "api#order_statuses", :via => :get

  match "/api/change_order_status" => "api#change_order_status", :via => :post
  match "/api/delete_pict" => "api#delete_pict", :via => :post
  match "/api/delete_product" => "api#delete_product", :via => :post
  match "/api/new_product" => "api#new_product", :via => :post
  match "/api/edit_business" => "api#edit_business", :via => :post
  match "/api/check_token" => "api#check_token", :via => :post
  match "/api/create_order" => "api#create_order", :via => :post
  match "/api/edit_product" => "api#edit_product", :via => :post
  match "/api/edit_profile" => "api#edit_profile", :via => :post

  match "/faqs/change_rank/:id" => "faqs#change_rank", :via => :get

  match "/businesses/change_theme/:id" => "businesses#change_theme", :via => :get
  match "/businesses/upload/:id" => "businesses#upload", :via => :get
  match "/sale_settings/remote_switch" => "sale_settings#remote_switch", :via => :get

  match "/home/sales" => "home#sales", :via => :get

  match "/orders/finilize/:id" => "orders#finilize", :via => :get

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:edit, :update, :destroy, :change_theme, :upload]
  before_action :load_business, only: [:index, :show,:change_theme, :upload]
    before_filter :authenticate_user!, :except => [:show]
    def upload

    end
  # GET /businesses
  # GET /businesses.json
  def change_theme
    @theme = Theme.find(params[:theme_id])
    @business.theme_id = @theme.id
    @business.save
    render :json => @business.to_json, :callback => params['callback']
  end
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show

  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)
    @business.save
    extract_classifications
    respond_to do |format|
      format.html { redirect_to "/businesses/upload/#{@business.id}", notice: 'Product was successfully updated.' }
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    @business.update(business_params)
    extract_classifications
    respond_to do |format|
      format.html { redirect_to "/businesses/upload/#{@business.id}", notice: 'Product was successfully updated.' }
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def extract_classifications
    @classifications = Classification.where(business_id: @business.id)
    for classification in @classifications
      classification.destroy
    end
    for key in params.keys
      if key.split('-')[0] == 'category'
        Classification.create(business_id: @business.id, category_id: params[key])
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:title, :user_id, :tel, :mobile, :fax, :address, :bio, :telegram_channel, :instagram_page, :email, :subdomain)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business_sidebar.html.erb
<div class="card card-profile">
  <div class="card-header" style="background-color: #3e668a;"></div>
  <div class="card-body text-center">
    <%= image_tag business.logo(:medium), class: "card-profile-img"%>
    <h3 class="mb-3"><%= link_to business.title, business%></h3>
    <ul class="social-links list-inline mb-0 mt-2">
      <li class="list-inline-item mb-0">
        <a href="javascript:void(0)" title="" data-toggle="tooltip" data-original-title="Facebook" aria-describedby="tooltip244372"><i class="fe fe-at-sign"></i></a>
      </li>
      <li class="list-inline-item">
        <a href="javascript:void(0)" title="" data-toggle="tooltip" data-original-title="Twitter"><i class="fa fa-instagram"></i></a>
      </li>
      <li class="list-inline-item">
        <a href="javascript:void(0)" title="" data-toggle="tooltip" data-original-title="1234567890"><i class="fa fa-telegram"></i></a>
      </li>

    </ul>
  </div>
</div>

app/views/businesses/_change_theme.html.erb
<div id='settings-detail'>
  <h5><%=t :change_theme%></h5>
  <div class="form-group">
    <div class="form-label mb-3"><%=t :choose_your_favourite_color%></div>
    <div class="custom-controls-stacked">
      <% for theme in Theme.all%>
      <label class="custom-control custom-radio">
        <input type="radio" class="custom-control-input" name="example-radios" value="<%= theme.id%>" <% if @business.theme_id == theme.id%>checked<%end%>>
        <div class="custom-control-label pr-5">
          <span class="colorinput-color" style='margin-top: -4px;background-color:<%= theme.header_background%>'></span>
        </div>
      </label>
      <%end%>
    </div>
  </div>
  <script>
  $('.custom-control-input').change(function() {
    var id = this.value;

      $.ajax({
        url: '/businesses/change_theme/'+<%=@business.id%>,
        type: 'GET',
        dataType: 'json',
        data: {
          theme_id: id
        },
        error: function() {

        },
        success: function() {
          location.reload();
        }
      });
  });
  </script>
</div>

app/views/businesses/_form.html.erb
<%= form_for(@business, html: {class: 'card'}) do |f| %>
<div class="card-header">
  <h3 class="card-title"><%=t :yout_business_details %></h3>
</div>
<% if @business.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

  <ul>
    <% @business.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="card-body">
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :title, class: "form-label" %>
        <%= f.text_field :title , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :subdomain, class: "form-label" %>
        <%= f.text_field :subdomain , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :tel, class: "form-label" %>
        <div class="input-group">
          <%= f.text_field :tel, class: "form-control", placeholder: "", style: 'direction: ltr;' %>
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-phone" aria-hidden="true"></i></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :mobile, class: "form-label" %>
        <div class="input-group">
          <%= f.text_field :mobile, class: "form-control", placeholder: "", style: 'direction: ltr;' %>
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-tablet" aria-hidden="true"></i></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :fax, class: "form-label" %>
        <div class="input-group">
          <%= f.text_field :fax , class: "form-control", placeholder: "" , style: 'direction: ltr;'%>
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-fax" aria-hidden="true"></i></span>
          </span>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :telegram_channel, class: "form-label" %>
        <div class="input-group">
          <%= f.text_field :telegram_channel , class: "form-control", placeholder: "" , style: 'direction: ltr;'%>
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-telegram" aria-hidden="true"></i></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :instagram_page, class: "form-label" %>
        <div class="input-group">
          <%= f.text_field :instagram_page , class: "form-control", placeholder: "", style: 'direction: ltr;' %>
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-instagram" aria-hidden="true"></i></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :email, class: "form-label" %>
        <div class="input-group">
          <%= f.text_field :email , class: "form-control", placeholder: "", style: 'direction: ltr;' %>
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text">@</span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :address, class: "form-label" %>
        <%= f.text_area :address , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :bio, class: "form-label" %>
        <%= f.text_area :bio , class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label class="form-label"><%=t :business_category%></label>
        <% for category in Category.where(level: 1)%>
        <% @classification = Classification.where(category_id: category.id, business_id: @business.id).first%>
        <label class="custom-control custom-checkbox custom-control-inline">
          <input type="checkbox" class="custom-control-input" name="category-<%= category.id%>" id="category-<%= category.id%>" <%if !@classification.blank?%>checked<%end%> value="<%= category.id%>">
          <span class="custom-control-label" style='padding-right: 23px;padding-top: 2px;'><%= category.title%></span>
        </label>
        <%end%>
      </div>
    </div>
  </div>

  <div class="card-footer text-right">
    <button type="submit" class="btn btn-primary"><%=t :submit%></button>
  </div>
  <% end %>

app/views/businesses/index.html.erb
<div class="row row-cards">
  <div class="col-lg-3">
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="card">
      <table class="table card-table table-vcenter">
        <tbody>
          <% @businesses.each do |business| %>
          <tr>
                        <td><%= business.title %></td>
                        <td><%= business.user_id %></td>
                        <td><%= business.tel %></td>
                        <td><%= business.mobile %></td>
                        <td><%= business.fax %></td>
                        <td><%= business.address %></td>
                        <td><%= business.bio %></td>
                        <td><%= business.telegram_channel %></td>
                        <td><%= business.instagram_page %></td>
                        <td><%= business.email %></td>
                        <td><%= link_to t(:show), business %></td>
            <td><%= link_to t(:edit), edit_business_path(business) %></td>
            <td><%= link_to t(:destroy), business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/businesses/show.html.erb
<div class='row'>
  <div class="col-lg-3  mb-4">
    <%= render partial: 'businesses/business_sidebar', locals: {business: @business}%>
    <!-- Getting started -->
    <% if !current_user.blank? %>
    <% if current_user.id == @business.user_id%>
    <div class="list-group list-group-transparent mb-4 text-center">
      <%= link_to '/businesses/'+@business.id.to_s+'/edit', class: "list-group-item list-group-item-action active small", style:'font-weight:normal;' do%>
      <i class="fe fe-edit" style="vertical-align:middle;"></i> <%=t :edit_your_business%>
      <%end%>
    </div>
    <%end%>
    <%end%>

  </div>
  <div class="col-lg-9 order-lg-1">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
        <div class="card-options">
          <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
        </div>
      </div>
      <div class="card-body">
        <div class='row'>
          <div class='col-md-12 col-lg-12'>
            <div class="form-group">
              <%= label :business, :title , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.title %></div>
            </div>
            <div class="form-group">
              <%= label :business, :tel , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.tel %></div>
            </div>
            <div class="form-group">
              <%= label :business, :mobile , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.mobile %></div>
            </div>
            <div class="form-group">
              <%= label :business, :fax , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.fax %></div>
            </div>
            <div class="form-group">
              <%= label :business, :address , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.address %></div>
            </div>
            <div class="form-group">
              <%= label :business, :bio , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.bio %></div>
            </div>
            <div class="form-group">
              <%= label :business, :telegram_channel , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.telegram_channel %></div>
            </div>
            <div class="form-group">
              <%= label :business, :instagram_page , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.instagram_page %></div>
            </div>
            <div class="form-group">
              <%= label :business, :email , class: "form-label strong"%>
              <div class="form-control-plaintext"><%= @business.email %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/upload.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%=t :crop_image%></h4>
      </div>
      <div class="modal-body">
           <img id="target" for="" src=""/>
           <input id="crop_x" name="upload[crop_x]" type="hidden" value="">
           <input id="crop_y" name="upload[crop_y]" type="hidden" value="">
           <input id="crop_w" name="upload[crop_w]" type="hidden" value="">
           <input id="crop_h" name="upload[crop_h]" type="hidden" value="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" onclick="send()"><%=t :submit%></button>
      </div>
    </div>
  </div>
</div>
<script>
function send(){
$.ajax({
type: "PATCH",
dataType: 'JSON',
url: '/uploads/'+ $('#target').attr('for'),
data: {authenticity_token: window._token, 'upload[crop_x]': $('#crop_x').val(), 'upload[crop_y]': $('#crop_y').val(), 'upload[crop_w]': $('#crop_w').val(), 'upload[crop_h]': $('#crop_h').val()},
success: function(){
   $('#target').attr('src', '');
   $('#myModal').modal('toggle');
}
});
}
</script>
<%= form_for(Upload.new, html: {class: 'dropzone'}) do |f| %>
<%= f.hidden_field :uploadable_type, value: 'Business'%>
<%= f.hidden_field :uploadable_id, value: @business.id%>
<%= f.hidden_field :attachment_type, value: 'business_logo'%>
<%= hidden_field_tag :file_type, 'picture'%>
<div class="fallback">
  <%= f.file_field :picture %><br>
  <%= f.hidden_field :uploadable_type, value: 'Business'%>
  <%= f.hidden_field :uploadable_id, value: @business.id%>
  <%= f.hidden_field :attachment_type, value: 'business_logo'%>
  <%= f.submit "Upload" %>
</div>
<% end %>
<script>
Dropzone.autoDiscover = false;
$("#new_upload").dropzone({
  dictDefaultMessage : "<%=t :drop_files_here_to_upload%>",
  dictRemoveFile : "<%=t :remove_file %>",
  acceptedFiles : '.docx,.doc,.pdf,.txt, .png,.jpg,.jpeg',
  addRemoveLinks: true,
  removedfile: function(file) {
    $.get( "/uploads/remoted/" + file.id, function( data ) {
      console.log(data);
    });
    var _ref;
    return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
  },
  init: function () {
    this.on("success", function(file, responseText) {
      $('#myModal').modal('show');
      $('#target').attr('src', responseText.image);
      $('#target').attr('for', responseText.id);
      $(function() {
        $('#target').Jcrop({
          onChange: update_crop,
          onSelect: update_crop,
          setSelect: [0, 0, 500, 500],
          aspectRatio: 1/1
        });
      });
      function update_crop(coords) {
        var ratio = responseText.ratio
        $('#crop_x').val(Math.floor(coords.x * ratio));
        $('#crop_y').val(Math.floor(coords.y * ratio));
        $('#crop_w').val(Math.floor(coords.w * ratio));
        $('#crop_h').val(Math.floor(coords.h * ratio));
      }
      file.id = responseText.id;
    });

    <% for upload in Upload.where(uploadable_type: 'Business', uploadable_id: @business.id, attachment_type: 'business_logo')%>
    var mockFile = { name: "<%= upload.attachment_file_name%>", size: <%= upload.attachment_file_size%>, url: "<%= upload.attachment.url%>", id: <%= upload.id%> };
    this.options.addedfile.call(this, mockFile);
    this.options.thumbnail.call(this, mockFile, "<%= upload.attachment(:large)%>");
    mockFile.previewElement.classList.add('dz-success');
    mockFile.previewElement.classList.add('dz-complete');
    <%end%>
  }
});
</script>