config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  resources :order_statuses
  resources :order_items
  resources :orders
  resources :pixels
  resources :themes
  resources :faqs
  resources :visits
  resources :segmentations
  resources :segments
  resources :cart_items
  resources :carts
  resources :prominents
  resources :likes
  resources :uploads
  resources :specifications
  resources :profiles
  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :specs
  resources :categories
  resources :classifications
  resources :categorizations
  resources :products
  resources :businesses
  get '', to: 'home#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root 'home#index'

  match "/categories/get_children/:id" => "categories#get_children", :via => :get
  match "/categories/specs/:id" => "categories#specs", :via => :get
  match "/categories/upload/:id" => "categories#upload", :via => :get

  match "/products/upload/:id" => "products#upload", :via => :get
  match "/uploads/remoted/:id" => "uploads#remoted", :via => :get

  match "/likes/liike/:id" => "likes#liike", :via => :get
  match "/likes/disliike/:id" => "likes#disliike", :via => :get

  match "/carts/add_to_cart/:id" => "carts#add_to_cart", :via => :get
  match "/carts/remove_from_cart/:id" => "carts#remove_from_cart", :via => :get

  match "/home/settings" => "home#settings", :via => :get

  match "/segments/check/:id" => "segments#check", :via => :get
  match "/segments/change_level/:id" => "segments#change_level", :via => :get
  match "/segments/add_to_segment/:id" => "segments#add_to_segment", :via => :get
  match "/segments/remove_from_segment/:id" => "segments#remove_from_segment", :via => :get

  match "/products/search/:id" => "products#search", :via => :get

  match "/api/segments" => "api#segments", :via => :get
  match "/api/products/:id" => "api#products", :via => :get
  match "/api/business" => "api#business", :via => :get
  match "/api/new_user" => "api#new_user", :via => :post
  match "/api/my_profile" => "api#my_profile", :via => :get
  match "/api/upload_pict" => "api#upload_pict", :via => :post
  match "/api/categories" => "api#categories", :via => :get
  match "/api/paginated_products" => "api#paginated_products", :via => :get
  match "/api/slider" => "api#slider", :via => :get
  match "/api/login" => "api#login", :via => :get
  match "/api/product_picts/:id" => "api#product_picts", :via => :get
  match "/api/provinces" => "api#provinces", :via => :get
  match "/api/orders/:id" => "api#orders", :via => :get
  match "/api/my_orders" => "api#my_orders", :via => :get
  match "/api/search" => "api#search", :via => :get
  match "/api/sort" => "api#sort", :via => :get
  match "/api/order_statuses" => "api#order_statuses", :via => :get

  match "/api/change_order_status" => "api#change_order_status", :via => :post
  match "/api/delete_pict" => "api#delete_pict", :via => :post
  match "/api/delete_product" => "api#delete_product", :via => :post
  match "/api/new_product" => "api#new_product", :via => :post
  match "/api/edit_business" => "api#edit_business", :via => :post
  match "/api/check_token" => "api#check_token", :via => :post
  match "/api/create_order" => "api#create_order", :via => :post
  match "/api/edit_product" => "api#edit_product", :via => :post
  match "/api/edit_profile" => "api#edit_profile", :via => :post

  match "/faqs/change_rank/:id" => "faqs#change_rank", :via => :get

  match "/businesses/change_theme/:id" => "businesses#change_theme", :via => :get
  match "/businesses/upload/:id" => "businesses#upload", :via => :get
  match "/sale_settings/remote_switch" => "sale_settings#remote_switch", :via => :get

  match "/home/sales" => "home#sales", :via => :get

  match "/orders/finilize/:id" => "orders#finilize", :via => :get

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :visitable, :polymorphic => true
  belongs_to :product, :class_name => "Product", :foreign_key => "visitable_id"
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:visitable_id, :visitable_type, :visitor_session)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit, html: {class: 'card'}) do |f| %>
<div class="card-header">
  <h3 class="card-title"><%=t :new_visit %></h3>
</div>
<% if @visit.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

  <ul>
    <% @visit.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="card-body">
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
          <%= f.label :visitable_id, class: "form-label" %>
      <%= f.number_field :visitable_id , class: "form-control" %>
          </div>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
          <%= f.label :visitable_type, class: "form-label" %>
      <%= f.text_field :visitable_type , class: "form-control" %>
          </div>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
          <%= f.label :visitor_session, class: "form-label" %>
      <%= f.text_field :visitor_session , class: "form-control" %>
          </div>
  </div>
</div>
<div class="card-footer text-right">
  <button type="submit" class="btn btn-primary"><%=t :submit%></button>
</div>
<% end %>

app/views/visits/index.html.erb
<div class="row row-cards">
  <div class="col-lg-3">
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="card">
      <table class="table card-table table-vcenter">
        <tbody>
          <% @visits.each do |visit| %>
          <tr>
                        <td><%= visit.visitable_id %></td>
                        <td><%= visit.visitable_type %></td>
                        <td><%= visit.visitor_session %></td>
                        <td><%= link_to t(:show), visit %></td>
            <td><%= link_to t(:edit), edit_visit_path(visit) %></td>
            <td><%= link_to t(:destroy), visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/visits/show.html.erb
<div class='row'>
  <div class="col-lg-4 order-lg-1">
  </div>
  <div class="col-lg-8 order-lg-1">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
        <div class="card-options">
          <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
        </div>
      </div>
      <div class="card-body">
        <div class='row'>
          <div class='col-md-12 col-lg-12'>
                        <div class="form-group">
              <%= label :visit, :visitable_id , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @visit.visitable_id %></div>
            </div>
                        <div class="form-group">
              <%= label :visit, :visitable_type , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @visit.visitable_type %></div>
            </div>
                        <div class="form-group">
              <%= label :visit, :visitor_session , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @visit.visitor_session %></div>
            </div>
                      </div>
        </div>
      </div>
    </div>
  </div>
</div>