config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  resources :order_statuses
  resources :order_items
  resources :orders
  resources :pixels
  resources :themes
  resources :faqs
  resources :visits
  resources :segmentations
  resources :segments
  resources :cart_items
  resources :carts
  resources :prominents
  resources :likes
  resources :uploads
  resources :specifications
  resources :profiles
  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :specs
  resources :categories
  resources :classifications
  resources :categorizations
  resources :products
  resources :businesses
  get '', to: 'home#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root 'home#index'

  match "/categories/get_children/:id" => "categories#get_children", :via => :get
  match "/categories/specs/:id" => "categories#specs", :via => :get
  match "/categories/upload/:id" => "categories#upload", :via => :get

  match "/products/upload/:id" => "products#upload", :via => :get
  match "/uploads/remoted/:id" => "uploads#remoted", :via => :get

  match "/likes/liike/:id" => "likes#liike", :via => :get
  match "/likes/disliike/:id" => "likes#disliike", :via => :get

  match "/carts/add_to_cart/:id" => "carts#add_to_cart", :via => :get
  match "/carts/remove_from_cart/:id" => "carts#remove_from_cart", :via => :get

  match "/home/settings" => "home#settings", :via => :get

  match "/segments/check/:id" => "segments#check", :via => :get
  match "/segments/change_level/:id" => "segments#change_level", :via => :get
  match "/segments/add_to_segment/:id" => "segments#add_to_segment", :via => :get
  match "/segments/remove_from_segment/:id" => "segments#remove_from_segment", :via => :get

  match "/products/search/:id" => "products#search", :via => :get

  match "/api/segments" => "api#segments", :via => :get
  match "/api/products/:id" => "api#products", :via => :get
  match "/api/business" => "api#business", :via => :get
  match "/api/new_user" => "api#new_user", :via => :post
  match "/api/my_profile" => "api#my_profile", :via => :get
  match "/api/upload_pict" => "api#upload_pict", :via => :post
  match "/api/categories" => "api#categories", :via => :get
  match "/api/paginated_products" => "api#paginated_products", :via => :get
  match "/api/slider" => "api#slider", :via => :get
  match "/api/login" => "api#login", :via => :get
  match "/api/product_picts/:id" => "api#product_picts", :via => :get
  match "/api/provinces" => "api#provinces", :via => :get
  match "/api/orders/:id" => "api#orders", :via => :get
  match "/api/my_orders" => "api#my_orders", :via => :get
  match "/api/search" => "api#search", :via => :get
  match "/api/sort" => "api#sort", :via => :get
  match "/api/order_statuses" => "api#order_statuses", :via => :get

  match "/api/change_order_status" => "api#change_order_status", :via => :post
  match "/api/delete_pict" => "api#delete_pict", :via => :post
  match "/api/delete_product" => "api#delete_product", :via => :post
  match "/api/new_product" => "api#new_product", :via => :post
  match "/api/edit_business" => "api#edit_business", :via => :post
  match "/api/check_token" => "api#check_token", :via => :post
  match "/api/create_order" => "api#create_order", :via => :post
  match "/api/edit_product" => "api#edit_product", :via => :post
  match "/api/edit_profile" => "api#edit_profile", :via => :post

  match "/faqs/change_rank/:id" => "faqs#change_rank", :via => :get

  match "/businesses/change_theme/:id" => "businesses#change_theme", :via => :get
  match "/businesses/upload/:id" => "businesses#upload", :via => :get
  match "/sale_settings/remote_switch" => "sale_settings#remote_switch", :via => :get

  match "/home/sales" => "home#sales", :via => :get

  match "/orders/finilize/:id" => "orders#finilize", :via => :get

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  has_many :products, :through => :segmentations
  has_many :segmentations, dependent: :destroy
  belongs_to :business
  before_create :determine_level

  def produkts
    if self.ext_code.blank?
      return self.products
    else
      return Product.find_by_sql(self.ext_code)
    end
  end

  def determine_level
    @segment = Segment.all.order('level desc').first
    if !@segment.blank?
      self.level = @segment.level.to_i + 1
    else
      self.level = 0
    end
  end

  def level_down
    self.level = self.level - 1
    self.save
  end

  def level_up
    self.level = self.level + 1
    self.save
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy, :check, :change_level, :add_to_segment, :remove_from_segment]
  before_action :load_business, only: [:create,:check, :change_level, :add_to_segment, :destroy, :remove_from_segment]
  # GET /segments
  # GET /segments.json


  def remove_from_segment
    @product = Product.find(params[:product_id])
    @segmentation = @segment.segmentations.where(product_id: @product.id).first
    @segmentation.destroy
  end
  def add_to_segment
    @product = Product.find(params[:product_id])
    @segment.segmentations.create(product_id: @product.id)
  end
  def change_level
    if params[:to] == 'up'
      @segment.level = @segment.level.to_i + 1
    else
      @segment.level = @segment.level.to_i - 1
    end
    @segment.save
  end

  def check
    if params[:to] == 'check'
      @segment.view_in_homepage = true
    else
      @segment.view_in_homepage = false
    end
    @segment.save
  end

  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)
    @segment.business_id = @business.id
    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:title)
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_business_segment.html.erb
<div id='settings-detail'>
<h5><%=t :new_segment%></h5>
<hr class="mt-2 mb-2"/>
<%= render partial: 'segments/remote_form', locals: {segment: Segment.new}%>
<h5><%=t :segments%></h5>
<hr class="mt-2 mb-2"/>
<%for segment in @business.segments.order('level desc, updated_at asc')%>
  <%= render partial: 'products/scrollable_block', locals: {segment: segment, caller: 'settings'}%>
<%end%>
</div>

app/views/segments/_form.html.erb
<%= form_for(@segment, html: {class: 'card'}) do |f| %>
<div class="card-header">
  <h3 class="card-title"><%=t :new_segment %></h3>
</div>
<% if @segment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

  <ul>
    <% @segment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="card-body">
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
          <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title , class: "form-control" %>
          </div>
  </div>
</div>
<div class="card-footer text-right">
  <button type="submit" class="btn btn-primary"><%=t :submit%></button>
</div>
<% end %>

app/views/segments/_remote_form.html.erb
<%= form_for(segment, remote: true) do |f| %>
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
      <div class="input-group">
        <%= f.text_field :title , class: "form-control", placeholder: t(:enter_segment_title) %>
        <span class="input-group-append">
          <button type="submit" class="btn btn-primary" type="button"><%=t :submit%></button>
        </span>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/segments/_segment_add_bar.html.erb
<div class='card-inner'>
  <div class='row'>
    <div class='col-md-6 col-12'>
      <%= form_tag '/products/search/1', method: :get, remote: true do |f| %>
      <div class="input-icon">
        <input type="text" name='q' class="form-control" autocomplete="off" placeholder="<%=t :search%>">
        <span class="input-icon-addon">
          <i class="fe fe-search"></i>
        </span>
      </div>
      <%= hidden_field_tag 'segment_id', segment.id%>
      <%end%>
    </div>
    <div class='col-md-6'>
    </div>
  </div>
  <%= render partial: 'products/segment_search' , locals:{segment: segment, products: []}%>
</div>

app/views/segments/_segment_options.html.erb
<div class="col-md-6 col-12 p-0 text-right">
<label class="custom-switch mt-1" style='float: left;'>
  <input type="checkbox" name="view_<%= segment.id%>" id='view_<%= segment.id%>' <%if segment.view_in_homepage%>checked<%end%> class="custom-switch-input">
  <span class="custom-switch-indicator"></span>
  <span class="custom-switch-description" style='font-size: 60%;'><%=t :view_in_the_first_page%></span>
</label>
</div>

<div class="col-md-5 col-12 p-0 text-right">
<% if @business.segments.order('level desc, updated_at asc').first.id != segment.id%>
<%= link_to "/segments/change_level/#{segment.id}?to=up", class: "icon", remote: true do %>
<i class="fe fe-chevrons-up" style='vertical-align:-3px;'></i>
<%end%>
<%else%>
<span class='icon'><i class="fe fe-chevrons-up" style='vertical-align:-3px;color:#f2f4f9'></i></span>
<%end%>
<span  style='font-size: 70%; padding-top: 5px;'><%=t :level %></span>
<% if @business.segments.order('level desc, updated_at asc').last.id != segment.id%>
<%= link_to "/segments/change_level/#{segment.id}?to=down", class: "icon", remote: true do %>
<i class="fe fe-chevrons-down" style='vertical-align:-3px;'></i>
<%end%>
<%else%>
<span class='icon'><i class="fe fe-chevrons-up" style='vertical-align:-3px;color:#f2f4f9'></i></span>
<%end%>
</div>

<div class="col-md-1 col-12 p-0 text-right">
<% if segment.ext_code.blank?%>
<%= link_to segment, method: :delete, remote: true, class: "icon" ,data: { confirm: 'Are you sure?' } do %>
<i class="fe fe-trash" style='vertical-align:-3px;'></i>
<%end%>
<%end%>
</div>

app/views/segments/index.html.erb
<div class="row row-cards">
  <div class="col-lg-3">
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="card">
      <table class="table card-table table-vcenter">
        <tbody>
          <% @segments.each do |segment| %>
          <tr>
                        <td><%= segment.title %></td>
                        <td><%= link_to t(:show), segment %></td>
            <td><%= link_to t(:edit), edit_segment_path(segment) %></td>
            <td><%= link_to t(:destroy), segment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/segments/show.html.erb
<div class='row'>
  <div class="col-lg-4 order-lg-1">
  </div>
  <div class="col-lg-8 order-lg-1">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
        <div class="card-options">
          <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
        </div>
      </div>
      <div class="card-body">
        <div class='row'>
          <div class='col-md-12 col-lg-12'>
                        <div class="form-group">
              <%= label :segment, :title , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @segment.title %></div>
            </div>
                      </div>
        </div>
      </div>
    </div>
  </div>
</div>