config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  resources :order_statuses
  resources :order_items
  resources :orders
  resources :pixels
  resources :themes
  resources :faqs
  resources :visits
  resources :segmentations
  resources :segments
  resources :cart_items
  resources :carts
  resources :prominents
  resources :likes
  resources :uploads
  resources :specifications
  resources :profiles
  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :specs
  resources :categories
  resources :classifications
  resources :categorizations
  resources :products
  resources :businesses
  get '', to: 'home#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root 'home#index'

  match "/categories/get_children/:id" => "categories#get_children", :via => :get
  match "/categories/specs/:id" => "categories#specs", :via => :get
  match "/categories/upload/:id" => "categories#upload", :via => :get

  match "/products/upload/:id" => "products#upload", :via => :get
  match "/uploads/remoted/:id" => "uploads#remoted", :via => :get

  match "/likes/liike/:id" => "likes#liike", :via => :get
  match "/likes/disliike/:id" => "likes#disliike", :via => :get

  match "/carts/add_to_cart/:id" => "carts#add_to_cart", :via => :get
  match "/carts/remove_from_cart/:id" => "carts#remove_from_cart", :via => :get

  match "/home/settings" => "home#settings", :via => :get

  match "/segments/check/:id" => "segments#check", :via => :get
  match "/segments/change_level/:id" => "segments#change_level", :via => :get
  match "/segments/add_to_segment/:id" => "segments#add_to_segment", :via => :get
  match "/segments/remove_from_segment/:id" => "segments#remove_from_segment", :via => :get

  match "/products/search/:id" => "products#search", :via => :get

  match "/api/segments" => "api#segments", :via => :get
  match "/api/products/:id" => "api#products", :via => :get
  match "/api/business" => "api#business", :via => :get
  match "/api/new_user" => "api#new_user", :via => :post
  match "/api/my_profile" => "api#my_profile", :via => :get
  match "/api/upload_pict" => "api#upload_pict", :via => :post
  match "/api/categories" => "api#categories", :via => :get
  match "/api/paginated_products" => "api#paginated_products", :via => :get
  match "/api/slider" => "api#slider", :via => :get
  match "/api/login" => "api#login", :via => :get
  match "/api/product_picts/:id" => "api#product_picts", :via => :get
  match "/api/provinces" => "api#provinces", :via => :get
  match "/api/orders/:id" => "api#orders", :via => :get
  match "/api/my_orders" => "api#my_orders", :via => :get
  match "/api/search" => "api#search", :via => :get
  match "/api/sort" => "api#sort", :via => :get
  match "/api/order_statuses" => "api#order_statuses", :via => :get

  match "/api/change_order_status" => "api#change_order_status", :via => :post
  match "/api/delete_pict" => "api#delete_pict", :via => :post
  match "/api/delete_product" => "api#delete_product", :via => :post
  match "/api/new_product" => "api#new_product", :via => :post
  match "/api/edit_business" => "api#edit_business", :via => :post
  match "/api/check_token" => "api#check_token", :via => :post
  match "/api/create_order" => "api#create_order", :via => :post
  match "/api/edit_product" => "api#edit_product", :via => :post
  match "/api/edit_profile" => "api#edit_profile", :via => :post

  match "/faqs/change_rank/:id" => "faqs#change_rank", :via => :get

  match "/businesses/change_theme/:id" => "businesses#change_theme", :via => :get
  match "/businesses/upload/:id" => "businesses#upload", :via => :get
  match "/sale_settings/remote_switch" => "sale_settings#remote_switch", :via => :get

  match "/home/sales" => "home#sales", :via => :get

  match "/orders/finilize/:id" => "orders#finilize", :via => :get

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :businesses, :through => :classifications
  has_many :classifications, dependent: :destroy

  has_many :products, :through => :categorizations
  has_many :categorizations, dependent: :destroy

  has_many :pixels

  def children
    return Category.where(parent_id: self.id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :specs, :upload]
  before_action :load_business, only: [:show, :index, :edit, :update, :create, :upload]
  def get_children
    @categories = Category.where(parent_id: params[:category_id])
    resp = []
    for k in @categories
      resp << {'title' => k.title, 'id' => k.id}
    end
    render :json => resp.to_json, :callback => params['callback']
  end

  def specs
    @specs = Spec.where(category_id: @category.id)
    resp = []
    for k in @specs
      resp << {'title' => k.title, 'id' => k.id}
    end
    render :json => resp.to_json, :callback => params['callback']
  end
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to "/categories/upload/#{@category.id}", notice: 'Product was successfully updated.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to "/categories/upload/#{@category.id}", notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :parent_id, :level)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: {class: 'card'}) do |f| %>
<div class="card-header">
  <h3 class="card-title"><%=t :new_category %></h3>
</div>
<% if @category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

  <ul>
    <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="card-body">
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
          <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title , class: "form-control" %>
          </div>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
          <%= f.label :parent_id, class: "form-label" %>
      <%= f.number_field :parent_id , class: "form-control" %>
          </div>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
          <%= f.label :level, class: "form-label" %>
      <%= f.number_field :level , class: "form-control" %>
          </div>
  </div>
</div>
<div class="card-footer text-right">
  <button type="submit" class="btn btn-primary"><%=t :submit%></button>
</div>
<% end %>

app/views/categories/index.html.erb
<div class="row row-cards">
  <div class="col-lg-3">
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="card">
      <table class="table card-table table-vcenter">
        <tbody>
          <% @categories.each do |category| %>
          <tr>
                        <td><%= category.title %></td>
                        <td><%= category.parent_id %></td>
                        <td><%= category.level %></td>
                        <td><%= link_to t(:show), category %></td>
            <td><%= link_to t(:edit), edit_category_path(category) %></td>
            <td><%= link_to t(:destroy), category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class='row'>
  <div class="col-lg-4 order-lg-1">
  </div>
  <div class="col-lg-8 order-lg-1">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
        <div class="card-options">
          <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
        </div>
      </div>
      <div class="card-body">
        <div class='row'>
          <div class='col-md-12 col-lg-12'>
                        <div class="form-group">
              <%= label :category, :title , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @category.title %></div>
            </div>
                        <div class="form-group">
              <%= label :category, :parent_id , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @category.parent_id %></div>
            </div>
                        <div class="form-group">
              <%= label :category, :level , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @category.level %></div>
            </div>
                      </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/upload.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title"><%=t :upload_pictures%></h3>
  </div>
  <div class="card-body">
    <%= form_for(Upload.new, html: {class: 'dropzone'}) do |f| %>
    <%= f.hidden_field :uploadable_type, value: 'Category'%>
    <%= f.hidden_field :uploadable_id, value: @category.id%>
    <%= f.hidden_field :attachment_type, value: 'category_attachment'%>
    <%= hidden_field_tag :file_type, 'picture'%>
    <div class="fallback">
      <%= f.file_field :picture %><br>
      <%= f.hidden_field :uploadable_type, value: 'Category'%>
      <%= f.hidden_field :uploadable_id, value: @category.id%>
      <%= f.hidden_field :attachment_type, value: 'category_attachment'%>
      <%= f.submit "Upload" %>
    </div>
    <% end %>
    <script>
    Dropzone.autoDiscover = false;
    $("#new_upload").dropzone({
      dictDefaultMessage : "<%=t :drop_files_here_to_upload%>",
      dictRemoveFile : "<%=t :remove_file %>",
      acceptedFiles : '.docx,.doc,.pdf,.txt, .png,.jpg,.jpeg',
      addRemoveLinks: true,
      removedfile: function(file) {
        $.get( "/uploads/remoted/" + file.id, function( data ) {
          console.log(data);
        });
        var _ref;
        return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
      },
      init: function () {
        this.on("success", function(file, responseText) {
          file.id = responseText.id;
        });

        <% for upload in Upload.where(uploadable_type: 'Category', uploadable_id: @category.id, attachment_type: 'category_attachment')%>
        var mockFile = { name: "<%= upload.attachment_file_name%>", size: <%= upload.attachment_file_size%>, url: "<%= upload.attachment.url%>", id: <%= upload.id%> };
        this.options.addedfile.call(this, mockFile);
        this.options.thumbnail.call(this, mockFile, "<%= upload.attachment(:large)%>");
        mockFile.previewElement.classList.add('dz-success');
        mockFile.previewElement.classList.add('dz-complete');
        <%end%>
      }
    });
    </script>
  </div>
  <div class="card-footer text-right">
    <a href='/categories/<%= @category.id%>' class="btn btn-lime"><%=t :submit_and_view%></a>
  </div>
</div>